### PR TITLE
Add FBX InheritRrs support

### PR DESCRIPTION
**Pull request by kamyarinfinity**
## Overview
FBX file format supports three different types of transformation inheritance:
- **eInheritRrSs:** Scaling of parent is applied in the child world after the local child rotation.
- **eInheritRSrs:** Scaling of parent is applied in the parent world.
- **eInheritRrs:** Scaling of parent does not affect the scaling of children.

This PR will add support for the third mode of inheritance which is used by joint hierarchy in Maya.

## TL;DR
This PR will not break anything, however to make use of the added feature, the PR for art tool should be also merged.

## Problem
The natural way to apply transformations is the second mode, eInheritRSrs, which is the default for most of the time. In one case, Maya breaks this default mode and that's for joint hierarchy or bones.

These other modes of inheritance are not supported by most of the fbx importers, even Autodesk 3dsmax doesn't support it, see [here](http://download.autodesk.com/us/fbx/fbx_maya_online/files/WS73099cc142f48755-3d114b751181c40f14b1283.htm). Facebook FBX2glTF converter has faced the same [issue](https://github.com/facebookincubator/FBX2glTF/issues/27) as well, which currently uses a [hack](https://github.com/facebookincubator/FBX2glTF/blob/d38ccd935f855a777082e4d9164d662381e4faf5/src/fbx/Fbx2Raw.cpp#L598) that only works with joints having identity scale. Unity didn't support this, and recently added support for it, but it has its limitations, [here](https://answers.unity.com/questions/1413998/scale-compensate-supported-or-not-supported.html) and [here](https://docs.unity3d.com/Manual/HOWTO-ImportObjectsFrom3DApps.html).

Overall, the issue is these other modes of inheritance may help the modeler, but are not natural and are somehow ambiguous in a transformation hierarchy, and require lots of unnecessary calculations to support them fully, or using hacks to make it work in some cases.

## Solution
To add support for this inheritance, there are 3 different places that needed modification.

1. **FBX Converter:**
   - Extract inherit types
   - Extract Local nodes hierarchy. Previously, all the transformations were chained together and we had no information if a node is a local transformation.
   - Create a backward compatible change in JSON spec:
      a. If an object has an inherit type which is not the default RSrs mode, save it in the node.
      b. For all the local nodes, add a `local-to` property which holds the name of the node which it is a local transformation for.
```javascript
"object1": {
      ...
     "inherit-type": 2
},
"object1_local_rot": {
      ...
     "local-to": "object1"
}
```

This way we can track which nodes in the hierarchy are local. These two properties are optional and dropping them, would just revert to the default calculation and hence a backward-compatible change.
These changes are applied to the converter are ready to merged in a separate PR.

 2. **Renderer:**
    - Previously, all the nodes in the hierarchy were multiplied to create the final global transformation.
    - To support the Rrs mode, we have to separate all the local nodes from the rest, and then only keep the scaling of the local node.
    - Should only do this if the inherit type is not the default RSrs mode.
    - To compensate scaling, instead of decomposing the whole matrix, only get the scale from the global matrix, inverse it, and inject it **in between** the local and the global matrices (more info in comments on the code):
```python
	Parent_Matrix = T * R * S
	Local_Matrix   = inv_S * (t * r * s)

 	Global_Matrix = Parent_Matrix * Local_Matrix
	Global_Matrix = (T * R * S) * (inv_S * t * r * s)
	Global_Matrix = (T * R) * (S * inv_S) * (t * r * s)
	Global_Matrix = (T * R) * (t * r * s)
```

## Migration

Merging this PR in itself is safe, as it should work the same for the old masks. However, to create masks that use the feature added in PR, a new version of FBX converter should be used. To enable safe migration, without breaking current workflow with possible issues in the new converter, a new option is added in the art tool to only use the new converter if the `BUILD BETA` button is pressed. This way, in case of issues, the old converter is still usable as before, until the new version gets stable.
build_beta_mode_pub

## Known Limitations

The eInheritRrSs mode support is not added, as it's not used by default in Maya or 3dsmax, so currently it's not worth the time/computation cost it needs. We'll have the data in our json files, and in case that becomes necessary, we can add that in a separate PR.

## Results
chicken-compare

### CODE REVIEW

**Comment by kamyarinfinity** [comment]
Jake found a bug with one of his masks. Delay merging until I address that bug.

**Comment by kamyarinfinity** [comment]
The problem was coming from the FBX converter, and was not related to this PR. The bug has been fixed in a commit to the other PR.

**Comment by glaba13** [comment]
Looks great for me. 
Just a comment from a quick look, I see that shared pointer is turned to a normal pointer type,
is it released from memory correctly and doesn't have any memory leaks from that?

**Comment by kamyarinfinity** [comment]
Thanks Guri for reviewing the code. If you take a look at the `PartCalcMatrix` in the original code, you see in the first line, the shared pointer is also converted to a normal pointer, so nothing regarding memory management should have changed.
Apart from that, it shouldn't create leaks and memory problems, as the function is having a read-only access to the shared pointer which has its memory managed elsewhere.
Let me know if you see any issues with this.

**Comment by kamyarinfinity** [comment]
Jake found another issue which I'm working on. Hold on merging yet.

**Comment by kamyarinfinity** [comment]
Latest commit will do the full matrix decomposition for figuring out the correct transform. This is different from what was discussed above about compensating scale from parents. The general idea is laid out below:

1. Extract Translation and transform it separately.
2. Compensate scale matrix _only_ for direct parent, and not from the global parent matrix. This required changing fbx converter to include local transform nodes info for default nodes as well. This change is added to Art Tool PR.

Here is an overview of the change. As you can see, we need to decompose after applying transformations, and we cannot use the local scale, rotation, translation information directly.
```python
Global_SR = Local_S * Parent_Global_S_NonLocal * Local_R * Parent_Global_R
Global_T  = Local_T_After_Local_Transforms * Parent_Global_Tranform
Transform = Global_SR * Global_T
```
Decomposition is done using the following method:
```python
# compute length of rows of the matrix M
S = (length(M[0]), length(M[1]), length(M[2]))
# more info about negative scaling  case:
# http://callumhay.blogspot.com/2010/10/decomposing-affine-transforms.html
if det(S) < 0:
   S[0] *= -1
T = M(3)
R = 1/S * M
```
Note that everything is written assuming we have row major matrices.

**Comment by brankalakic** [comment]
Good job!

**Pull request merged**
