### PR TITLE
Anti-aliasing Feature

### PR DESCRIPTION
**Pull request by kamyarinfinity**
## Overview 
This PR adds anti-aliasing effect to facemask models. This will fix jagged edges appearing on straight lines.
There are two general types methods implemented:

- **Super-sampled Anti-aliasing (SSAA):** It gives the best result, but it has to render twice as big.
- **Fast Approximation Anti-aliasing (FXAA):** It is a smarter approach that finds the edges and applies the effect to only those areas. It has a subtler effect in its original form. In this implementation I had to add a final averaging to make the effect more announced, as excessive noisy movements makes the aliasing effect harder to solve.

## Results

In this video the result of SSAA and FXAA can be compared with no anti-aliasing:
demo_aa_small

The following image compares the methods side by side:
aa_compare_final

## User Interface

To make it easier to change the method used, an option is added under the debug options for face mask plugin. As this may be beneficial to end-users to change the method or even disable AA, we may move this to main set of options for face mask.

options

### CODE REVIEW

**Comment by glaba13** [comment]
this PR is amazing ^_^

**Comment by kamyarinfinity** [comment]
@glaba13 Thanks 😄

**Comment by kamyarinfinity** [comment]
Thanks to Branka, the issue with loading face mask plugin was fixed, tbb.dll had to be moved to the plugin folder as well, for the new version.

**Comment by glaba13** [comment]
@kamyarinfinity  In CmakeLists all new effects should be added for made in the distrib folder automatically:

Example:
```
SET(facemask-plugin_DATA
	"${PROJECT_SOURCE_DIR}/data/effects/color_alpha_tex.effect"
	"${PROJECT_SOURCE_DIR}/data/effects/color_conversion.effect"
	"${PROJECT_SOURCE_DIR}/data/effects/default.effect"
	"${PROJECT_SOURCE_DIR}/data/effects/denoise.effect"
	"${PROJECT_SOURCE_DIR}/data/effects/merge.effect"
	"${PROJECT_SOURCE_DIR}/data/effects/phong.effect"
	"${PROJECT_SOURCE_DIR}/data/locale/en-US.ini"
)

```
simply add a new file

**Comment by kamyarinfinity** [comment]
@glaba13 I see! Thanks for fixing that.

**Comment by kamyarinfinity** [comment]
Revert changes were not reflected fully in this branch. Merged from staging to make the build consistent.

**Pull request merged**
